GET http://localhost:8000/api/posts HTTP/1.1

###
POST http://localhost:8000/api/posts HTTP/1.1
Content-type: application/json

{
    "title": "My new title copnt",
    "content": "My new content cont"
}
### 
PUT http://localhost:8000/api/posts/3 HTTP/1.1
Content-type: application/json

{
    "title": "My updatedddd title 3",
    "content": "My updatedddd content 3"
}
###
GET http://localhost:8000/api/posts/3 HTTP/1.1
###
POST http://localhost:8000/api/posts HTTP/1.1
Content-type: application/json

{
    "title": "My new title to delete",
    "content": "My new content delete"
}
###   
DELETE http://localhost:8000/api/posts/8 HTTP/1.1